django_summernote/models.py
Cuando se deseaba reutilizar un adjunto dentro del admin, con relaciones foraneas, no era posible ver el nombre del archivo porque dicho objeto no estaba configurado para ello.
=> Corregido el nombre del objeto al usar FK

README.md, django_summernote/admin.py, django_summernote/models.py, django_summernote/settings.py, django_summernote/templates/django_summernote/widget_iframe_editor.html, django_summernote/templates/django_summernote/widget_inplace.html, django_summernote/tests.py, django_summernote/views.py
- Added new feature to use "custom attachment model" for holding additional data fields.
- Additional parameters can be passed to both widgets as attributes (starting with "-data").
Proposed approach:
- Exposing a new abstract model "AbstractAttachment", available to be subclassed.
- New method settings.get_attachment_model() is used to determine appropriate Attachment model (default: django_summernote.Attachment).
- Additional attributes parameters are collected in widget JavaScript and POSTed back to server as data body.
=> Introducing Custom Attachment

README.md, django_summernote/urls.py
Django 1.10 won't support the deprecated django.conf.urls.patterns.
=> Removed deprecated patterns syntax

README.md, django_summernote/settings.py, django_summernote/tests.py
- Added simple test for custom attachment model
- Ensure ImproperlyConfigured exception is raised when model specified in SUMMERNOTE_CONFIG["attachment_model"] is not inherited from AbstractAttachment.
=> Added test for custom attachment model

README.md
`manage.py syncdb` has been removed in the latest of Django.
So I fixed README.
--
https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9
> The syncdb command is removed.
=> Delete from the README of syncdb command

django_summernote/views.py
This is a simple fix to add i18n to the HTTP responses when uploading images.
The output from these responses is currently just displayed in a JS alert.
=> Added translated strings in views

django_summernote/templates/django_summernote/widget_inplace.html, django_summernote/widgets.py
This is a fixup for PR #126 commits 4faa7e4 - Ability to enable/disable
upload images.
That update provided a 'disable_upload' setting which is then honored
in the iframe widget, but did not include cooresponding updates for the
inplace widget.
This commit includes two changes:
1. widget_inplace.html: Mirror the if..endif logic from
widget_iframe_editor.html to prevent defining onImageUpload if
disable_upload is True.
2. widgets.SummernoteInplaceWidget.render: Mirror the update to
views.editor, placing the value of disable_upload in the render context
for the inplace widget.
=> Allow inplace widget to honor disable_upload setting.

django_summernote/widgets.py
This fixes file upload from inplace widget, which was broken in #155. This closes #165.
=> Added missing CSRF_COOKIE_NAME to inplace widget (fixes #165)

.gitignore
I use PyCharm IDE which generates .idea files for configurations.
I want them to be ignored.
=> ignore pycharm configuration files

.travis.yml
Hello,
I just removed "setuptools" in order not to install for travis-ci test.
I'm not sure what's wrong, but it now builds successfully.
[travis-ci build result](https://travis-ci.org/pincoin/django-summernote)
Thank you.
=> - travis-ci build error fix

django_summernote/static/django_summernote/jquery.fileupload.js, django_summernote/static/django_summernote/jquery.iframe-transport.js, django_summernote/templates/django_summernote/widget_iframe_editor.html, django_summernote/templates/django_summernote/widget_inplace.html
Hello,
The [jQuery official documents](http://api.jquery.com/jquery.ajax/) notify the deprecated API:
> Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.
I substituted jQuery Ajax function `success()` and `error()` to `done()` and `fail()`.
jQuery 1.x and 2.x support both `success()` and `done()`. That's why this PR works fine with jQuery 1.x, 2.x and 3.x.
I also upgraded jQuery-File-Upload version to v9.19.0.
Thank you.
=> - jQuery 3.x AJAX API compatible

django_summernote/settings.py, django_summernote/views.py, django_summernote/widgets.py
Hello,
I removed duplicate css/js declarations, and it is just code refactoring not related to features.
I often made a mistake to test several library versions like jquery, bootstrap, jquery-file-upload.
* `base_css` and `base_js` declare its environment such as jQuery and Bootstrap.
* `default_css` and `default_js` delcare the summernote itself.
* `css` and `js` can be used for additional declarations for `SummernoteWidget`.
* `css_for_inplace` and `js_for_inplace` can be used for additional declarations for `SummernoteInplaceWidget`.
I also updated the jQuery and Bootstrap version for `SummernoteWidget`.
Please, review the code and accept this PR.
Thank you.
=> Remove duplicate css/js declarations

django_summernote/settings.py, django_summernote/templates/django_summernote/widget_iframe_editor.html, django_summernote/templates/django_summernote/widget_inplace.html, django_summernote/widgets.py
For https://github.com/summernote/django-summernote/issues/53
Now we can use different name for calling `jQuery`.
=> Add jquery variable setting to use another name

setup.py
Hello,
Our `django-summernote` package supports 3.6 Python.
We need to update the package meta information.
Thank you.
=> Python setuptools classifiers updated

MANIFEST.in, setup.py
Hello,
`djs_playground` package was added, but it shouldn't be included in PyPI package.
`find_package()` searches all the available packages, and `djs_playground` has `__init__.py`. That's why this package is added automatically although `manage.py` is not included in PyPI package.
Thank you.
=> Exclude djs_playground package explicitly

README.md, django_summernote/widgets.py
This patch allows user can add external plugin settings via dict.
Like this;
```
SUMMERNOTE_CONFIG = {                                                               
'summernote': {                                                                 
'print': {                                                                  
'stylesheetUrl': '/static/print.css',                                   
},                                                                          
},                                                                              
'js': (                                                                         
'/static/summernote-ext-print.js',                                          
),  
}
```
=> Allow user can add external plugin settings via dict.

django_summernote/widgets.py
Added check summernote language is not 'en-US' before adding i18n script
=> Fixed django storage issues with summernote lang = 'en-US' settings

README.md
Hi, I've added some missing commas in example `SUMMERNOTE_CONFIG` in `README.md`.
Thanks :)
=> Add some missing commas for SUMMERNOTE_CONFIG in README.md

django_summernote/widgets.py
As see [Django's roadmap](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjHo8Kg8c7XAhVGe7wKHQXJDOkQFgglMAA&url=https%3A%2F%2Fwww.djangoproject.com%2Fweblog%2F2015%2Fjun%2F25%2Froadmap%2F&usg=AOvVaw2YvmZ2NGXcJYzMz0zGba_2), we do not have to support under Django 1.7 at all. So I dropped it.
=> Dropping support under Django 1.7

.gitignore, django_summernote/views.py, django_summernote/widgets.py, djs_playground/views.py
Hello,
Thanks to #245 @minusf, I was able to find my faults that I made two widgets mangled.
I changed the code as follows:
1. `SummernoteInplaceWidget` uses static definition as before.
2. `SummernoteWidget` renders static path of assets in `django_summernote/views.py`.
I really appreciate @minusf PR, but I also agree that static definition could be better than dynamic property.
Therefore, @minusf PR could be turned down if this PR is accepted.
Thank you.
=> form assets error fix

django_summernote/models.py
We're already dropped support under Python 2.7, but we're still using a try-except block for them. So I removed it.
=> Drop support under Python 2.7

django_summernote/test_settings.py, django_summernote/tests.py, django_summernote/views.py, tox.ini
Hello,
- MIDDLEWARE instead of MIDDLEWARE_CLASSES as of Django 1.10.
- Cascaded option specified for Foreign key
- Using User.is_authenticated() as methods rather than properties is no longer supported as of Django 2.0
- Django 2.0 does NOT support Python 2.x.
=> django 2.0 supported

django_summernote/static/summernote/ResizeSensor.js
Fix from @shapeshifta78 https://github.com/marcj/css-element-queries/pull/154
=> Fixes ResizeSensor.js: TypeError: window.getComputedStyle(...) is null

README.md, django_summernote/admin.py, django_summernote/templates/django_summernote/widget_common.html
Call recalcHeight function in iframe only.Otherwise recalcHeight function will reset wysiwyg editor height after  wysiwyg editor been full screen in SummernoteInplaceWidget.
=> Fix SummernoteInplaceWidget full screen not work bug.

django_summernote/admin.py
Unable to override dbfield. Arguments for formfield_for_dbfield has been changed since 1.10
https://github.com/django/django/commit/dbb0df2a0ec5bee80bee336fc81408efb30b7e47#diff-3c42de3e53aba87b32c494f995a728df
=> Django 1.11 compatibility issue

django_summernote/templates/django_summernote/widget_common.html
Any existing value in the textarea was not being copied over to summernote when using `SummernoteInplaceWidget`. This is a supersmall fix for that problem.
=> Bugfix: Existing value not used for inplace widget

django_summernote/widgets.py
If pop is used to get the value of 'summernote' on self.attrs, then the html returned by render() may change after the first call.  For example:
```python
w=SummernoteWidget(attrs={'summernote':{'height':'123px'}})
w.render('test','',attrs={'id':'test'})
```
Will render the iframe height as '123px', however a second call 
```python
w.render('test','',attrs={'id':'test'})
```
will render whatever the default value for height is instead of '123px' because the summernote value of attrs was popped in the first call and therefore is no longer available for subsequent calls.
This PR fixes that by chaning the self.attrs.pop('summernote', {}) calls in both widgets to self.attrs.get('summernote', {})
=> fix widget repeat rendering

README.md
If you copy the SUMMERNOTE_CONFIG in README.md to settings, and use summernote form
TypeError is occurred
here is the detail 
"
TypeError at /summernote/editor/id_content/
can only concatenate tuple (not "set") to tuple
"
=> css in SUMMERNOTE_CONFIG is not a dict, it's be a tuple

django_summernote/apps.py, django_summernote/templates/django_summernote/upload_attachment.json, django_summernote/views.py
By turning `attachment_absolute_uri` on, attachment paths will be returned in absolute URIs.
This fixes #351
=> Add attachment_absolute_uri

django_summernote/models.py
Removes "Attachment object (1)" error on listings
=> Python3 + Django 2.x support

README.md, django_summernote/utils.py, django_summernote/views.py, django_summernote/widgets.py, setup.py
This commit fixes https://github.com/summernote/django-summernote/issues/344
In README.md, the `codemirror` related settings were at the top of config.
For now, we should pass the `codemirror` settings to `summernote library(js)` together with `config ['summernote']`.
- Find key `codemirror` in `config ['summernote']`, not config.
- Updated the out-dated README.md to match the current implementation.
- Also, i modified `setup.py` to install only on Python versions lower than 3.3 when testing.
=> Fix logic to check the existence of codemirror config

django_summernote/apps.py
There is a small typo in django_summernote/apps.py.
Should read `backward` rather than `backword`.
=> docs: Fix simple typo, backword -> backward

README.md
Fixing the form usage documentation to refer to the right field class: SummernoteTextField.
=> Fix the README.md to use the right field class

README.md, django_summernote/views.py
Hello, I was wondering what you would think of setting X-Frame-Options on a per-view basis, rather than having users specify `X_FRAME_OPTIONS` for the entire site in the settings file? This would allow the site still to run with the default `X-Frame-Options: DENY` for general security, while letting the Summernote frames through.
I notice this has been suggested by @mimi89999 in https://github.com/summernote/django-summernote/issues/381#issuecomment-565726657, but I wasn't sure what the outcome of that was.
In our project we only use the text editors (we don't use file attachments), so I might not have caught every relevant spot—let me know if I missed something.
Thanks for your work on this package, it's been a godsend for us!
=> Set X-Frame-Options setting on a per-view basis

djs_playground/urls.py
Changing the URL deprecated method for the re_path method.
#441
=> Change url in favor of the re_path

django_summernote/test_django_summernote.py
There is a small typo in django_summernote/test_django_summernote.py.
Should read `attachment` rather than `attachement`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, attachement -> attachment

django_summernote/apps.py
https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys
=> set default_auto_field to silence django 3.2 warnings
